create table "public"."todo_lists" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "content" text not null,
    "is_completed" boolean not null default false,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


alter table "public"."todo_lists" enable row level security;

CREATE UNIQUE INDEX todo_lists_pkey ON public.todo_lists USING btree (id);

alter table "public"."todo_lists" add constraint "todo_lists_pkey" PRIMARY KEY using index "todo_lists_pkey";

alter table "public"."todo_lists" add constraint "todo_lists_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) not valid;

alter table "public"."todo_lists" validate constraint "todo_lists_task_id_fkey";


